export const REACT_QUERY_KEYS = {
  VIEW_MY_PROFILE: "VIEW_MY_PROFILE",
  VIEW_GAMES_LIST: "VIEW_GAMES_LIST",
  VIEW_BLOGS_LIST: "VIEW_BLOGS_LIST",
  VIEW_FRIENDS_LIST: "VIEW_FRIENDS_LIST",
  VIEW_FRIENDS_SUGGESTIONS_LIST: "VIEW_FRIENDS_SUGGESTIONS_LIST",
  GET_CATEGORIES: "GET_CATEGORIES",
};
